logging:
    level:
        root: info
        jason.samples: debug
game:
    montyhall:
        number-of-doors: 3
        guest:
            strategy: keep-my-mind
            
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"